### ISSUE TITLE
cannot import name 'ChuckNorris'

### ISSUE THREAD

**Issue by riOwnage** [Keda87/chuck-norris-python#4] opened 2019-02-14 14:14 UTC
python3 chuck.py 
Traceback (most recent call last):
  File "chuck.py", line 3, in <module>
    from chuck import ChuckNorris
  File "/home/bruce/Documents/python/chuck.py", line 3, in <module>
    from chuck import ChuckNorris
ImportError: cannot import name 'ChuckNorris'

**Comment by Keda87** [comment] 2019-02-14 14:21
Hi, could you inform me what python version do you use?

**Comment by riOwnage** [comment] 2019-02-14 14:22
Hi

python3 -V
Python 3.6.7

**Comment by Keda87** [comment] 2019-02-14 17:07
@riOwnage works fine in mine. how you install the packge?
are you using `pip install chuck-norris-python` ?

**Comment by riOwnage** [comment] 2019-02-14 18:45
Hi Keda,

Actually I used pip3 install chuck-norris-python. Just installed it, no virtual env.
I now also installed pip install chuck-norris-python, when I go to my python27 dir it gives the same error..

**Comment by Keda87** [comment] 2019-02-15 13:28
HI @riOwnage ,
Sorry I have difficulties when debugging your issue.
I'm not sure with this issue because I've tried to test with some python versions and it works fine.

I also add more python version to ensure this package works.
https://travis-ci.org/Keda87/chuck-norris-python

have you tried in a different machine? or using pipenv?

**Comment by riOwnage** [comment] 2019-02-15 14:55
It says the same on different pcs with different OSs. In a virtualenvironment with jupyter notebook it can import "from chuck import ChuckNorris" on a windows machine I saw yesterday night. Did not try it further.

I simply installed python3.6 and 3.7 with pip3 installation.

with python3.7 i get more output:

Traceback (most recent call last):
  File "chuck.py", line 1, in <module>
    from chuck import ChuckNorris
  File "/home/bruce/Documents/python/chuck.py", line 1, in <module>
    from chuck import ChuckNorris
ImportError: cannot import name 'ChuckNorris' from 'chuck' (/home/bruce/Documents/python/chuck.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "chuck.py", line 1, in <module>
    from chuck import ChuckNorris
  File "/home/bruce/Documents/python/chuck.py", line 1, in <module>
    from chuck import ChuckNorris
ImportError: cannot import name 'ChuckNorris' from 'chuck' (/home/bruce/Documents/python/chuck.py)

**Comment by riOwnage** [comment] 2019-02-15 16:14
It only works in a virtual environment.. tried a lot without venv without success.

I just simply installed with pip "globally"
pip install chuck-norris-python
or
pip3 install chuck-norris-python

I use only this is in my python code:
from chuck import ChuckNorris

cn = ChuckNorris()

data = cn.random()
print(data.joke)

That works in venv, not globally

**Comment by Keda87** [comment] 2019-02-18 05:07
@riOwnage Sorry for the late response. I've tried in global environment and works as expected.
I'm worried that you have a problem on your python installation.

**Comment by Keda87** [comment] 2019-02-18 05:09
> python3 chuck.py
> Traceback (most recent call last):
> File "chuck.py", line 3, in 
> from chuck import ChuckNorris
> File "/home/bruce/Documents/python/chuck.py", line 3, in 
> from chuck import ChuckNorris
> ImportError: cannot import name 'ChuckNorris'

Also as you mentioned here, `chuck.py` file is located in your home documents dir.
and if you installed using pip, the file should live in your python installation dir.

**Comment by riOwnage** [comment] 2019-02-18 13:05
Hi Keda87,

No problem. I tried you solution still doesn't work.. 
Every other module just works, I have already tried this on three different OSs. Linux, Windows, Rasp Pi.

I think I leave this for now, thanks for your help so far.

**Comment by Keda87** [comment] 2019-02-18 15:20
@riOwnage Hi, sorry for your issue still not resolved.
I've tried in my VPS using ubuntu and python 3.6.5 in global environment and the package is successfully installed.

```
root@adiyatmubarak ~/Projects                                                                                                                                             [15:16:02]
> # python --version
Python 3.6.5

root@adiyatmubarak ~/Projects                                                                                                                                             [15:16:12]
> # pip install chuck-norris-python
Collecting chuck-norris-python
  Downloading https://files.pythonhosted.org/packages/0b/bb/621045540cc89fbad5915cdc0b4a6d2321b868deea79db3ea852873d9773/chuck-norris-python-1.1.tar.gz
Requirement already satisfied: requests in /root/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from chuck-norris-python) (2.18.4)
Requirement already satisfied: certifi>=2017.4.17 in /root/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests->chuck-norris-python) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /root/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests->chuck-norris-python) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /root/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests->chuck-norris-python) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /root/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests->chuck-norris-python) (1.22)
Installing collected packages: chuck-norris-python
  Running setup.py install for chuck-norris-python ... done
Successfully installed chuck-norris-python-1.1
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@adiyatmubarak ~/Projects                                                                                                                                             [15:16:26]
> # python
Python 3.6.5 (default, Apr 30 2018, 13:10:36)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chuck import ChuckNorris
>>> cn = ChuckNorris()
>>> dir(cn)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'base_url', 'get_all_jokes', 'get_jokes_by_id', 'get_jokes_categories', 'get_jokes_count', 'random']
>>> cn.random()
<Norris: The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.>
>>>
```

I will close this issue for now. If you have another information how to reproduce it, just leave a comment.

**Closed as completed by Keda87** 2019-02-18 15:20 UTC
